---
title: JufLisanne.nl
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    show_meta: false
    comments: false
    author: phlow
- scope:
    path: ''
    type: posts
  values:
    show_meta: true
    comments: false
    author: phlow
slogan: Enthousiaste kleuterjuf
description: 'JufLisanne.nl is een website vol met leuke lesideeën en inzichten over
  het huidige kleuteronderwijs. '
credits: <p>Created with &hearts; by <a href="http://phlow.de/">Phlow</a> with <a
  href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on <a href="http://phlow.github.io/feeling-responsive/">Feeling
  Responsive</a>.</p>
url: http://www.juflisanne.nl
baseurl: 
improve_content: https://github.com/lmlentink/lmlentink.github.io
urlimg: http://www.juflisanne.nl/images/
logo: logojuf.png
gems:
- jekyll-asciidoc
- jekyll-gist
- jekyll-paginate
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
permalink: "/:categories/:title/"
highlight: rouge
excerpt_separator: "<!--more-->"
include:
- ".htaccess"
exclude:
- ".sass-cache"
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- INSTALL.md
language: nl
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  profile: false
  ignore:
    envs:
    - development
sass:
  sass_dir: _sass
  style: compressed
asciidoctor-enabled: false
asciidoctor:
  description: testtewtetrue
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
